# Generated by Django 3.0.2 on 2020-01-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensehel_logs_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['timestamp']},
        ),
    ]
